project_id = "perfil-metabolico"

[api]
enabled = true
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 17

[db.migrations]
schema_paths = ["./schemas/*.sql"]

[auth]
enabled = true
site_url = "http://127.0.0.1:4174"
additional_redirect_urls = ["http://localhost:4174"]
enable_signup = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
